# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0b558248ba23abd6861a0a76702f8325"
name = "ReturnGuard-AI"
application_url = "https://startup1-bu7t.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_returns,read_products,read_customers"

[auth]
redirect_urls = [
  "https://startup1-bu7t.onrender.com/auth/callback",
  "https://startup1-bu7t.onrender.com/auth/shopify/callback",
  "https://startup1-bu7t.onrender.com/api/auth/callback",
]
